spring:
  datasource:
#    url: jdbc:mysql://39.108.208.253:3306/dayrecord?serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/record?serverTimezone=UTC
    url: jdbc:mysql://106.55.196.115:3306/record?serverTimezone=UTC
    #useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    druid:
      filter:
        encoding:
          enabled: true

  #开启文件上传配置
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
#mapper文件路径
mybatis-plus:
  mapper-locations: classpath*:Mapper/*.xml

